package interfaces;

import javax.swing.JFrame;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;

public class evalTicket extends javax.swing.JFrame {

    public evalTicket() {
        try {
            initComponents();
            this.setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE); //Desactiva el botón de cerrar
            setLocationRelativeTo(null); //Centra el jFrame
            UIManager.setLookAndFeel("java.swing.plaf.gtk.GTKLookAndFeel"); //Da el estilo al jFrame
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | UnsupportedLookAndFeelException ex) {
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btnQ1Angry = new javax.swing.JButton();
        btnQ1Soso = new javax.swing.JButton();
        btnQ1Medium = new javax.swing.JButton();
        btnQ1Happy = new javax.swing.JButton();
        btnQ1Love = new javax.swing.JButton();
        btnQ2Love = new javax.swing.JButton();
        btnQ2Happy = new javax.swing.JButton();
        btnQ2Medium = new javax.swing.JButton();
        btnQ2Soso = new javax.swing.JButton();
        btnQ2Angry = new javax.swing.JButton();
        btnQ3Love = new javax.swing.JButton();
        btnQ3Happy = new javax.swing.JButton();
        btnQ3Medium = new javax.swing.JButton();
        btnQ1Soso2 = new javax.swing.JButton();
        btnQ3Angry = new javax.swing.JButton();
        btnQ4Love = new javax.swing.JButton();
        btnQ4Happy = new javax.swing.JButton();
        btnQ4Medium = new javax.swing.JButton();
        btnQ4Soso = new javax.swing.JButton();
        btnQ4Angry = new javax.swing.JButton();
        lblFeelQ1 = new javax.swing.JLabel();
        lblFeelQ2 = new javax.swing.JLabel();
        lblFeelQ3 = new javax.swing.JLabel();
        lblFeelQ4 = new javax.swing.JLabel();
        btnEvaluate = new javax.swing.JButton();
        btnReturn = new javax.swing.JButton();
        lblBottom = new javax.swing.JLabel();
        lblBottom2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Evaluación de ticket");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("No. evaluación:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 12, -1, -1));

        jLabel2.setText("321");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(123, 12, -1, -1));

        jLabel3.setText("¿Cuán satisfactoria fue la solución a su solicitud?");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 60, -1, -1));

        jLabel4.setText("¿Cómo calificaría el tiempo de respuesta?");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 144, -1, -1));

        jLabel5.setText("¿Cómo calificaría la atención del especialista?");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 228, -1, -1));

        jLabel6.setText("¿Cómo calificaría los servicios que ofrece DIGESET?");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 312, -1, -1));

        btnQ1Angry.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/emoji_angry.png"))); // NOI18N
        btnQ1Angry.setToolTipText("Muy mala");
        btnQ1Angry.setBorder(null);
        btnQ1Angry.setBorderPainted(false);
        btnQ1Angry.setContentAreaFilled(false);
        getContentPane().add(btnQ1Angry, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 84, -1, -1));

        btnQ1Soso.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/emoji_sad.png"))); // NOI18N
        btnQ1Soso.setToolTipText("Mala");
        btnQ1Soso.setBorder(null);
        btnQ1Soso.setBorderPainted(false);
        btnQ1Soso.setContentAreaFilled(false);
        btnQ1Soso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQ1SosoActionPerformed(evt);
            }
        });
        getContentPane().add(btnQ1Soso, new org.netbeans.lib.awtextra.AbsoluteConstraints(66, 84, -1, -1));

        btnQ1Medium.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/emoji_confused.png"))); // NOI18N
        btnQ1Medium.setToolTipText("Normal");
        btnQ1Medium.setBorder(null);
        btnQ1Medium.setBorderPainted(false);
        btnQ1Medium.setContentAreaFilled(false);
        getContentPane().add(btnQ1Medium, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 84, -1, -1));

        btnQ1Happy.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/emoji.png"))); // NOI18N
        btnQ1Happy.setToolTipText("Buena");
        btnQ1Happy.setBorder(null);
        btnQ1Happy.setBorderPainted(false);
        btnQ1Happy.setContentAreaFilled(false);
        getContentPane().add(btnQ1Happy, new org.netbeans.lib.awtextra.AbsoluteConstraints(174, 84, -1, -1));

        btnQ1Love.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/emoji_in_love.png"))); // NOI18N
        btnQ1Love.setToolTipText("Muy buena");
        btnQ1Love.setBorder(null);
        btnQ1Love.setBorderPainted(false);
        btnQ1Love.setContentAreaFilled(false);
        getContentPane().add(btnQ1Love, new org.netbeans.lib.awtextra.AbsoluteConstraints(228, 84, -1, -1));

        btnQ2Love.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/emoji_in_love.png"))); // NOI18N
        btnQ2Love.setToolTipText("Muy buena");
        btnQ2Love.setBorder(null);
        btnQ2Love.setBorderPainted(false);
        btnQ2Love.setContentAreaFilled(false);
        getContentPane().add(btnQ2Love, new org.netbeans.lib.awtextra.AbsoluteConstraints(228, 168, -1, -1));

        btnQ2Happy.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/emoji.png"))); // NOI18N
        btnQ2Happy.setToolTipText("Buena");
        btnQ2Happy.setBorder(null);
        btnQ2Happy.setBorderPainted(false);
        btnQ2Happy.setContentAreaFilled(false);
        getContentPane().add(btnQ2Happy, new org.netbeans.lib.awtextra.AbsoluteConstraints(174, 168, -1, -1));

        btnQ2Medium.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/emoji_confused.png"))); // NOI18N
        btnQ2Medium.setToolTipText("Normal");
        btnQ2Medium.setBorder(null);
        btnQ2Medium.setBorderPainted(false);
        btnQ2Medium.setContentAreaFilled(false);
        getContentPane().add(btnQ2Medium, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 168, -1, -1));

        btnQ2Soso.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/emoji_sad.png"))); // NOI18N
        btnQ2Soso.setToolTipText("Mala");
        btnQ2Soso.setBorder(null);
        btnQ2Soso.setBorderPainted(false);
        btnQ2Soso.setContentAreaFilled(false);
        btnQ2Soso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQ2SosoActionPerformed(evt);
            }
        });
        getContentPane().add(btnQ2Soso, new org.netbeans.lib.awtextra.AbsoluteConstraints(66, 168, -1, -1));

        btnQ2Angry.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/emoji_angry.png"))); // NOI18N
        btnQ2Angry.setToolTipText("Muy mala");
        btnQ2Angry.setBorder(null);
        btnQ2Angry.setBorderPainted(false);
        btnQ2Angry.setContentAreaFilled(false);
        getContentPane().add(btnQ2Angry, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 168, -1, -1));

        btnQ3Love.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/emoji_in_love.png"))); // NOI18N
        btnQ3Love.setToolTipText("Muy buena");
        btnQ3Love.setBorder(null);
        btnQ3Love.setBorderPainted(false);
        btnQ3Love.setContentAreaFilled(false);
        getContentPane().add(btnQ3Love, new org.netbeans.lib.awtextra.AbsoluteConstraints(228, 252, -1, -1));

        btnQ3Happy.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/emoji.png"))); // NOI18N
        btnQ3Happy.setToolTipText("Buena");
        btnQ3Happy.setBorder(null);
        btnQ3Happy.setBorderPainted(false);
        btnQ3Happy.setContentAreaFilled(false);
        getContentPane().add(btnQ3Happy, new org.netbeans.lib.awtextra.AbsoluteConstraints(174, 252, -1, -1));

        btnQ3Medium.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/emoji_confused.png"))); // NOI18N
        btnQ3Medium.setToolTipText("Normal");
        btnQ3Medium.setBorder(null);
        btnQ3Medium.setBorderPainted(false);
        btnQ3Medium.setContentAreaFilled(false);
        getContentPane().add(btnQ3Medium, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 252, -1, -1));

        btnQ1Soso2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/emoji_sad.png"))); // NOI18N
        btnQ1Soso2.setToolTipText("Mala");
        btnQ1Soso2.setBorder(null);
        btnQ1Soso2.setBorderPainted(false);
        btnQ1Soso2.setContentAreaFilled(false);
        btnQ1Soso2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQ1Soso2ActionPerformed(evt);
            }
        });
        getContentPane().add(btnQ1Soso2, new org.netbeans.lib.awtextra.AbsoluteConstraints(66, 252, -1, -1));

        btnQ3Angry.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/emoji_angry.png"))); // NOI18N
        btnQ3Angry.setToolTipText("Muy mala");
        btnQ3Angry.setBorder(null);
        btnQ3Angry.setBorderPainted(false);
        btnQ3Angry.setContentAreaFilled(false);
        getContentPane().add(btnQ3Angry, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 252, -1, -1));

        btnQ4Love.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/emoji_in_love.png"))); // NOI18N
        btnQ4Love.setToolTipText("Muy buena");
        btnQ4Love.setBorder(null);
        btnQ4Love.setBorderPainted(false);
        btnQ4Love.setContentAreaFilled(false);
        getContentPane().add(btnQ4Love, new org.netbeans.lib.awtextra.AbsoluteConstraints(228, 342, -1, -1));

        btnQ4Happy.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/emoji.png"))); // NOI18N
        btnQ4Happy.setToolTipText("Buena");
        btnQ4Happy.setBorder(null);
        btnQ4Happy.setBorderPainted(false);
        btnQ4Happy.setContentAreaFilled(false);
        getContentPane().add(btnQ4Happy, new org.netbeans.lib.awtextra.AbsoluteConstraints(174, 342, -1, -1));

        btnQ4Medium.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/emoji_confused.png"))); // NOI18N
        btnQ4Medium.setToolTipText("Normal");
        btnQ4Medium.setBorder(null);
        btnQ4Medium.setBorderPainted(false);
        btnQ4Medium.setContentAreaFilled(false);
        getContentPane().add(btnQ4Medium, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 342, -1, -1));

        btnQ4Soso.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/emoji_sad.png"))); // NOI18N
        btnQ4Soso.setToolTipText("Mala");
        btnQ4Soso.setBorder(null);
        btnQ4Soso.setBorderPainted(false);
        btnQ4Soso.setContentAreaFilled(false);
        btnQ4Soso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQ4SosoActionPerformed(evt);
            }
        });
        getContentPane().add(btnQ4Soso, new org.netbeans.lib.awtextra.AbsoluteConstraints(66, 342, -1, -1));

        btnQ4Angry.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/emoji_angry.png"))); // NOI18N
        btnQ4Angry.setToolTipText("Muy mala");
        btnQ4Angry.setBorder(null);
        btnQ4Angry.setBorderPainted(false);
        btnQ4Angry.setContentAreaFilled(false);
        getContentPane().add(btnQ4Angry, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 342, -1, -1));

        lblFeelQ1.setText("Seleccione una opción...");
        getContentPane().add(lblFeelQ1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 100, -1, -1));

        lblFeelQ2.setText("Seleccione una opción...");
        getContentPane().add(lblFeelQ2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 180, -1, -1));

        lblFeelQ3.setText("Seleccione una opción...");
        getContentPane().add(lblFeelQ3, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 270, -1, -1));

        lblFeelQ4.setText("Seleccione una opción...");
        getContentPane().add(lblFeelQ4, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 360, -1, -1));

        btnEvaluate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/check_mark.png"))); // NOI18N
        btnEvaluate.setToolTipText("Evaluar");
        btnEvaluate.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnEvaluate.setBorderPainted(false);
        btnEvaluate.setContentAreaFilled(false);
        getContentPane().add(btnEvaluate, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 430, -1, -1));

        btnReturn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/left.png"))); // NOI18N
        btnReturn.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnReturn.setBorderPainted(false);
        btnReturn.setContentAreaFilled(false);
        btnReturn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReturnActionPerformed(evt);
            }
        });
        getContentPane().add(btnReturn, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 430, -1, -1));

        lblBottom.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/071770FB5.png"))); // NOI18N
        lblBottom.setToolTipText(null);
        getContentPane().add(lblBottom, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 480, 370));

        lblBottom2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/071770FB5.png"))); // NOI18N
        lblBottom2.setToolTipText(null);
        getContentPane().add(lblBottom2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 370, 480, 110));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnQ1SosoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQ1SosoActionPerformed
        
    }//GEN-LAST:event_btnQ1SosoActionPerformed

    private void btnQ2SosoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQ2SosoActionPerformed
        
    }//GEN-LAST:event_btnQ2SosoActionPerformed

    private void btnQ1Soso2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQ1Soso2ActionPerformed
        
    }//GEN-LAST:event_btnQ1Soso2ActionPerformed

    private void btnQ4SosoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQ4SosoActionPerformed
        
    }//GEN-LAST:event_btnQ4SosoActionPerformed

    private void btnReturnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReturnActionPerformed
        this.dispose();
        new main().setVisible(true);
    }//GEN-LAST:event_btnReturnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new evalTicket().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEvaluate;
    private javax.swing.JButton btnQ1Angry;
    private javax.swing.JButton btnQ1Happy;
    private javax.swing.JButton btnQ1Love;
    private javax.swing.JButton btnQ1Medium;
    private javax.swing.JButton btnQ1Soso;
    private javax.swing.JButton btnQ1Soso2;
    private javax.swing.JButton btnQ2Angry;
    private javax.swing.JButton btnQ2Happy;
    private javax.swing.JButton btnQ2Love;
    private javax.swing.JButton btnQ2Medium;
    private javax.swing.JButton btnQ2Soso;
    private javax.swing.JButton btnQ3Angry;
    private javax.swing.JButton btnQ3Happy;
    private javax.swing.JButton btnQ3Love;
    private javax.swing.JButton btnQ3Medium;
    private javax.swing.JButton btnQ4Angry;
    private javax.swing.JButton btnQ4Happy;
    private javax.swing.JButton btnQ4Love;
    private javax.swing.JButton btnQ4Medium;
    private javax.swing.JButton btnQ4Soso;
    private javax.swing.JButton btnReturn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel lblBottom;
    private javax.swing.JLabel lblBottom2;
    private javax.swing.JLabel lblFeelQ1;
    private javax.swing.JLabel lblFeelQ2;
    private javax.swing.JLabel lblFeelQ3;
    private javax.swing.JLabel lblFeelQ4;
    // End of variables declaration//GEN-END:variables
}
