/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaces;

import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;

/**
 *
 * @author barreola
 */
public class logBook extends javax.swing.JFrame {

    /**
     * Creates new form logBook
     */
    public logBook() {
        try {
            initComponents();
            this.setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE); //Desactiva el botón de cerrar
            setLocationRelativeTo(null); //Centra el jFrame
            UIManager.setLookAndFeel("java.swing.plaf.gtk.GTKLookAndFeel"); //Da el estilo al jFrame
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | UnsupportedLookAndFeelException ex) {
            Logger.getLogger(logBook.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        lblNo = new javax.swing.JLabel();
        lblNoReg = new javax.swing.JLabel();
        lblIn = new javax.swing.JLabel();
        cmbHourIn = new javax.swing.JComboBox<>();
        cmbMinutesIn = new javax.swing.JComboBox<>();
        lblOut = new javax.swing.JLabel();
        cmbHourOut = new javax.swing.JComboBox<>();
        cmbMinutesOut = new javax.swing.JComboBox<>();
        lblKmIn = new javax.swing.JLabel();
        lblKmOut = new javax.swing.JLabel();
        txtKmOut = new javax.swing.JTextField();
        txtKmIn = new javax.swing.JTextField();
        lblGasIn = new javax.swing.JLabel();
        lblGasOut = new javax.swing.JLabel();
        cmbGasIn = new javax.swing.JComboBox<>();
        cmbGasOut = new javax.swing.JComboBox<>();
        btnAdd = new javax.swing.JButton();
        btnReturn = new javax.swing.JButton();
        lblBottom = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblNo.setText("No. registro");
        getContentPane().add(lblNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        lblNoReg.setText("613");
        getContentPane().add(lblNoReg, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 10, -1, -1));

        lblIn.setText("Hora de entrada:");
        getContentPane().add(lblIn, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, -1));

        cmbHourIn.setFont(new java.awt.Font("Ubuntu", 0, 10)); // NOI18N
        cmbHourIn.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "00", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23" }));
        cmbHourIn.setToolTipText("Hora");
        getContentPane().add(cmbHourIn, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 110, 70, 20));

        cmbMinutesIn.setFont(new java.awt.Font("Ubuntu", 0, 10)); // NOI18N
        cmbMinutesIn.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31", "32", "33", "34", "35", "36", "37", "38", "39", "40", "41", "42", "43", "44", "45", "46", "47", "48", "49", "50", "51", "52", "53", "54", "55", "56", "57", "58", "59" }));
        cmbMinutesIn.setToolTipText("Minutos");
        getContentPane().add(cmbMinutesIn, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 110, 70, 20));

        lblOut.setText("Hora de salida:");
        getContentPane().add(lblOut, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, -1));

        cmbHourOut.setFont(new java.awt.Font("Ubuntu", 0, 10)); // NOI18N
        cmbHourOut.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "00", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23" }));
        cmbHourOut.setToolTipText("Hora");
        getContentPane().add(cmbHourOut, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 80, 70, 20));

        cmbMinutesOut.setFont(new java.awt.Font("Ubuntu", 0, 10)); // NOI18N
        cmbMinutesOut.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31", "32", "33", "34", "35", "36", "37", "38", "39", "40", "41", "42", "43", "44", "45", "46", "47", "48", "49", "50", "51", "52", "53", "54", "55", "56", "57", "58", "59" }));
        cmbMinutesOut.setToolTipText("Minutos");
        getContentPane().add(cmbMinutesOut, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 80, 70, 20));

        lblKmIn.setText("Kilometraje de entrada:");
        getContentPane().add(lblKmIn, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, -1, -1));

        lblKmOut.setText("Kilometraje de salida:");
        getContentPane().add(lblKmOut, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, -1, -1));

        txtKmOut.setFont(new java.awt.Font("Ubuntu", 0, 12)); // NOI18N
        txtKmOut.setToolTipText("Ingrese sólo números...");
        getContentPane().add(txtKmOut, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 160, 100, -1));

        txtKmIn.setFont(new java.awt.Font("Ubuntu", 0, 12)); // NOI18N
        txtKmIn.setToolTipText("Ingrese sólo números...");
        getContentPane().add(txtKmIn, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 200, 100, -1));

        lblGasIn.setText("Nivel de gas de entrada:");
        getContentPane().add(lblGasIn, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, -1, -1));

        lblGasOut.setText("Nivel de gas de salida:");
        getContentPane().add(lblGasOut, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, -1, -1));

        cmbGasIn.setFont(new java.awt.Font("Ubuntu", 0, 12)); // NOI18N
        cmbGasIn.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1/4", "1/2", "3/4", "Lleno" }));
        getContentPane().add(cmbGasIn, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 290, -1, -1));

        cmbGasOut.setFont(new java.awt.Font("Ubuntu", 0, 12)); // NOI18N
        cmbGasOut.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1/4", "1/2", "3/4", "Lleno" }));
        getContentPane().add(cmbGasOut, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 250, -1, -1));

        btnAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/add.png"))); // NOI18N
        btnAdd.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnAdd.setBorderPainted(false);
        btnAdd.setContentAreaFilled(false);
        getContentPane().add(btnAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 310, -1, -1));

        btnReturn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/left.png"))); // NOI18N
        btnReturn.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnReturn.setBorderPainted(false);
        btnReturn.setContentAreaFilled(false);
        btnReturn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReturnActionPerformed(evt);
            }
        });
        getContentPane().add(btnReturn, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 310, -1, -1));

        lblBottom.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/071770FB5.png"))); // NOI18N

        org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ObjectProperty.create(), lblBottom, org.jdesktop.beansbinding.BeanProperty.create("background"));
        bindingGroup.addBinding(binding);

        getContentPane().add(lblBottom, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 370));

        bindingGroup.bind();

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnReturnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReturnActionPerformed
        this.dispose();
        new main().setVisible(true);
    }//GEN-LAST:event_btnReturnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(logBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(logBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(logBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(logBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new logBook().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnReturn;
    private javax.swing.JComboBox<String> cmbGasIn;
    private javax.swing.JComboBox<String> cmbGasOut;
    private javax.swing.JComboBox<String> cmbHourIn;
    private javax.swing.JComboBox<String> cmbHourOut;
    private javax.swing.JComboBox<String> cmbMinutesIn;
    private javax.swing.JComboBox<String> cmbMinutesOut;
    private javax.swing.JLabel lblBottom;
    private javax.swing.JLabel lblGasIn;
    private javax.swing.JLabel lblGasOut;
    private javax.swing.JLabel lblIn;
    private javax.swing.JLabel lblKmIn;
    private javax.swing.JLabel lblKmOut;
    private javax.swing.JLabel lblNo;
    private javax.swing.JLabel lblNoReg;
    private javax.swing.JLabel lblOut;
    private javax.swing.JTextField txtKmIn;
    private javax.swing.JTextField txtKmOut;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables
}
