package interfaces;

import javax.swing.JFrame;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;

public class main extends javax.swing.JFrame {

    public main() {
        try {
            initComponents();
            this.setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE); //Desactiva el botón de cerrar
            setLocationRelativeTo(null); //Centra el jFrame
            UIManager.setLookAndFeel("java.swing.plaf.gtk.GTKLookAndFeel"); //Da el estilo al jFrame
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | UnsupportedLookAndFeelException ex) {
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnDepartments = new javax.swing.JButton();
        btnETickets = new javax.swing.JButton();
        btnBDC = new javax.swing.JButton();
        btnTickets = new javax.swing.JButton();
        btnServices = new javax.swing.JButton();
        btnVehicles = new javax.swing.JButton();
        btnWorkers = new javax.swing.JButton();
        btnLogOut = new javax.swing.JButton();
        btnLogBook = new javax.swing.JButton();
        lblBottom = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Principal");
        setName("frmMain"); // NOI18N
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnDepartments.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/business_office.png"))); // NOI18N
        btnDepartments.setToolTipText("Departamentos");
        btnDepartments.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnDepartments.setBorderPainted(false);
        btnDepartments.setContentAreaFilled(false);
        btnDepartments.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDepartmentsActionPerformed(evt);
            }
        });
        getContentPane().add(btnDepartments, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 150, -1, -1));

        btnETickets.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/attendance_list.png"))); // NOI18N
        btnETickets.setToolTipText("Evaluar ticket");
        btnETickets.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnETickets.setBorderPainted(false);
        btnETickets.setContentAreaFilled(false);
        btnETickets.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnETicketsActionPerformed(evt);
            }
        });
        getContentPane().add(btnETickets, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 150, -1, -1));

        btnBDC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/batch_process.png"))); // NOI18N
        btnBDC.setToolTipText("BD Conocimiento");
        btnBDC.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnBDC.setBorderPainted(false);
        btnBDC.setContentAreaFilled(false);
        btnBDC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBDCActionPerformed(evt);
            }
        });
        getContentPane().add(btnBDC, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 150, -1, -1));

        btnTickets.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/edit_1.png"))); // NOI18N
        btnTickets.setToolTipText("Tickets");
        btnTickets.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnTickets.setBorderPainted(false);
        btnTickets.setContentAreaFilled(false);
        btnTickets.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTicketsActionPerformed(evt);
            }
        });
        getContentPane().add(btnTickets, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, -1, -1));

        btnServices.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/services.png"))); // NOI18N
        btnServices.setToolTipText("Servicios");
        btnServices.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnServices.setBorderPainted(false);
        btnServices.setContentAreaFilled(false);
        btnServices.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnServicesActionPerformed(evt);
            }
        });
        getContentPane().add(btnServices, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 40, -1, -1));

        btnVehicles.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/plan_3_e.png"))); // NOI18N
        btnVehicles.setToolTipText("Vehículos");
        btnVehicles.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnVehicles.setBorderPainted(false);
        btnVehicles.setContentAreaFilled(false);
        btnVehicles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVehiclesActionPerformed(evt);
            }
        });
        getContentPane().add(btnVehicles, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 40, -1, -1));

        btnWorkers.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/group.png"))); // NOI18N
        btnWorkers.setToolTipText("Trabajadores");
        btnWorkers.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnWorkers.setBorderPainted(false);
        btnWorkers.setContentAreaFilled(false);
        btnWorkers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnWorkersActionPerformed(evt);
            }
        });
        getContentPane().add(btnWorkers, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 40, -1, -1));

        btnLogOut.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/outbox.png"))); // NOI18N
        btnLogOut.setToolTipText("Cerrar sesión");
        btnLogOut.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnLogOut.setBorderPainted(false);
        btnLogOut.setContentAreaFilled(false);
        btnLogOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogOutActionPerformed(evt);
            }
        });
        getContentPane().add(btnLogOut, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 270, -1, -1));

        btnLogBook.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/address_book 72.png"))); // NOI18N
        btnLogBook.setToolTipText("Bitácora");
        btnLogBook.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnLogBook.setBorderPainted(false);
        btnLogBook.setContentAreaFilled(false);
        btnLogBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogBookActionPerformed(evt);
            }
        });
        getContentPane().add(btnLogBook, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, -1, -1));

        lblBottom.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/071770FB5.png"))); // NOI18N
        lblBottom.setToolTipText(null);
        getContentPane().add(lblBottom, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 340));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDepartmentsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDepartmentsActionPerformed
        new department().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnDepartmentsActionPerformed

    private void btnServicesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnServicesActionPerformed
        new services().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnServicesActionPerformed

    private void btnLogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogOutActionPerformed
        new login().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnLogOutActionPerformed

    private void btnVehiclesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVehiclesActionPerformed
        new vehicles().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnVehiclesActionPerformed

    private void btnWorkersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnWorkersActionPerformed
        new workers().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnWorkersActionPerformed

    private void btnTicketsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTicketsActionPerformed
        new ticket().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnTicketsActionPerformed

    private void btnETicketsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnETicketsActionPerformed
        new evalTicket().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnETicketsActionPerformed

    private void btnBDCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBDCActionPerformed
        new knowledgeDB().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnBDCActionPerformed

    private void btnLogBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogBookActionPerformed
        new logBook().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnLogBookActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new main().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBDC;
    private javax.swing.JButton btnDepartments;
    private javax.swing.JButton btnETickets;
    private javax.swing.JButton btnLogBook;
    private javax.swing.JButton btnLogOut;
    private javax.swing.JButton btnServices;
    private javax.swing.JButton btnTickets;
    private javax.swing.JButton btnVehicles;
    private javax.swing.JButton btnWorkers;
    private javax.swing.JLabel lblBottom;
    // End of variables declaration//GEN-END:variables
}
