package interfaces;

import classes.ConnectionManager;
import java.awt.Image;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;

public class main extends javax.swing.JFrame {

    private int no_ticket;

    public main() {
        initComponents();
        formatJFrame();
        lblLogBook.setVisible(false);
        lblServices.setVisible(false);
        lblVehicles.setVisible(false);
        lblWorkers.setVisible(false);
        lblDependencies.setVisible(false);
        lblDepartments.setVisible(false);
        lblTickets.setVisible(false);
        lblBDC.setVisible(false);
        lblEval.setVisible(false);
    }

    private void formatJFrame() {
        try {
            this.setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE); //Desactiva el botón de cerrar
            setLocationRelativeTo(null); //Centra el jFrame
            UIManager.setLookAndFeel("com.sun.java.swing.plaf.gtk.GTKLookAndFeel"); //Da el estilo al jFrame
            this.pack();
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | UnsupportedLookAndFeelException ex) {
            ex.getMessage();
        }
    }

    private boolean validateNoTicket() {
        try {
            int ticket = 0;
            String status = "";
            Connection connection = ConnectionManager.getConnection();
            Statement select = connection.createStatement();
            ResultSet result = select.executeQuery("SELECT no_ticket, status from Ticket where no_ticket = " + no_ticket);

            while (result.next()) {
                ticket = result.getInt("no_ticket");
                status = result.getString("status");
            }

            if (ticket != 0 && status.equals("cerrado")){
                return true;
            }

            connection.close();
        } catch (SQLException ex) {
            return false;
        }
        return false;
    }

    @Override
    public Image getIconImage() {
        Image retValue = Toolkit.getDefaultToolkit().
                getImage(ClassLoader.getSystemResource("icons/program_icon.png"));
        return retValue;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnDepartments = new javax.swing.JButton();
        btnETickets = new javax.swing.JButton();
        btnBDC = new javax.swing.JButton();
        btnTickets = new javax.swing.JButton();
        btnServices = new javax.swing.JButton();
        btnVehicles = new javax.swing.JButton();
        btnWorkers = new javax.swing.JButton();
        btnLogOut = new javax.swing.JButton();
        btnLogBook = new javax.swing.JButton();
        btnDependencies = new javax.swing.JButton();
        lblLogBook = new javax.swing.JLabel();
        lblServices = new javax.swing.JLabel();
        lblVehicles = new javax.swing.JLabel();
        lblWorkers = new javax.swing.JLabel();
        lblDependencies = new javax.swing.JLabel();
        lblTickets = new javax.swing.JLabel();
        lblDepartments = new javax.swing.JLabel();
        lblEval = new javax.swing.JLabel();
        lblBDC = new javax.swing.JLabel();
        lblBottom = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Principal");
        setIconImage(getIconImage());
        setMaximumSize(new java.awt.Dimension(545, 335));
        setMinimumSize(new java.awt.Dimension(545, 335));
        setName("frmMain"); // NOI18N
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnDepartments.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/business_office.png"))); // NOI18N
        btnDepartments.setToolTipText("Departamentos");
        btnDepartments.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnDepartments.setBorderPainted(false);
        btnDepartments.setContentAreaFilled(false);
        btnDepartments.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnDepartmentsMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnDepartmentsMouseEntered(evt);
            }
        });
        btnDepartments.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDepartmentsActionPerformed(evt);
            }
        });
        getContentPane().add(btnDepartments, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 180, -1, -1));

        btnETickets.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/attendance_list.png"))); // NOI18N
        btnETickets.setToolTipText("Evaluar ticket");
        btnETickets.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnETickets.setBorderPainted(false);
        btnETickets.setContentAreaFilled(false);
        btnETickets.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnETicketsMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnETicketsMouseEntered(evt);
            }
        });
        btnETickets.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnETicketsActionPerformed(evt);
            }
        });
        getContentPane().add(btnETickets, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 180, -1, -1));

        btnBDC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/batch_process.png"))); // NOI18N
        btnBDC.setToolTipText("BD Conocimiento");
        btnBDC.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnBDC.setBorderPainted(false);
        btnBDC.setContentAreaFilled(false);
        btnBDC.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnBDCMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnBDCMouseEntered(evt);
            }
        });
        btnBDC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBDCActionPerformed(evt);
            }
        });
        getContentPane().add(btnBDC, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 180, -1, -1));

        btnTickets.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/edit.png"))); // NOI18N
        btnTickets.setToolTipText("Tickets");
        btnTickets.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnTickets.setBorderPainted(false);
        btnTickets.setContentAreaFilled(false);
        btnTickets.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnTicketsMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnTicketsMouseEntered(evt);
            }
        });
        btnTickets.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTicketsActionPerformed(evt);
            }
        });
        getContentPane().add(btnTickets, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, -1, -1));

        btnServices.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/services.png"))); // NOI18N
        btnServices.setToolTipText("Servicios");
        btnServices.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnServices.setBorderPainted(false);
        btnServices.setContentAreaFilled(false);
        btnServices.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnServicesMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnServicesMouseEntered(evt);
            }
        });
        btnServices.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnServicesActionPerformed(evt);
            }
        });
        getContentPane().add(btnServices, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 40, -1, -1));

        btnVehicles.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/plan_3_e.png"))); // NOI18N
        btnVehicles.setToolTipText("Vehículos");
        btnVehicles.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnVehicles.setBorderPainted(false);
        btnVehicles.setContentAreaFilled(false);
        btnVehicles.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnVehiclesMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnVehiclesMouseEntered(evt);
            }
        });
        btnVehicles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVehiclesActionPerformed(evt);
            }
        });
        getContentPane().add(btnVehicles, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 40, -1, -1));

        btnWorkers.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/group.png"))); // NOI18N
        btnWorkers.setToolTipText("Trabajadores");
        btnWorkers.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnWorkers.setBorderPainted(false);
        btnWorkers.setContentAreaFilled(false);
        btnWorkers.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnWorkersMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnWorkersMouseEntered(evt);
            }
        });
        btnWorkers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnWorkersActionPerformed(evt);
            }
        });
        getContentPane().add(btnWorkers, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 40, -1, -1));

        btnLogOut.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/outbox.png"))); // NOI18N
        btnLogOut.setToolTipText("Cerrar sesión");
        btnLogOut.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnLogOut.setBorderPainted(false);
        btnLogOut.setContentAreaFilled(false);
        btnLogOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogOutActionPerformed(evt);
            }
        });
        getContentPane().add(btnLogOut, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 320, -1, -1));

        btnLogBook.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/address_book 72.png"))); // NOI18N
        btnLogBook.setToolTipText("Bitácora");
        btnLogBook.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnLogBook.setBorderPainted(false);
        btnLogBook.setContentAreaFilled(false);
        btnLogBook.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnLogBookMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnLogBookMouseEntered(evt);
            }
        });
        btnLogBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogBookActionPerformed(evt);
            }
        });
        getContentPane().add(btnLogBook, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, -1, -1));

        btnDependencies.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/dependency.png"))); // NOI18N
        btnDependencies.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnDependencies.setBorderPainted(false);
        btnDependencies.setContentAreaFilled(false);
        btnDependencies.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnDependenciesMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnDependenciesMouseEntered(evt);
            }
        });
        btnDependencies.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDependenciesActionPerformed(evt);
            }
        });
        getContentPane().add(btnDependencies, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 40, -1, -1));

        lblLogBook.setText("Bitácora");
        getContentPane().add(lblLogBook, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, -1, -1));

        lblServices.setText("Servicios");
        getContentPane().add(lblServices, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 120, -1, -1));

        lblVehicles.setText("Vehículos");
        getContentPane().add(lblVehicles, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 120, -1, -1));

        lblWorkers.setText("Trabajadores");
        getContentPane().add(lblWorkers, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 120, -1, -1));

        lblDependencies.setText("Dependencias");
        getContentPane().add(lblDependencies, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 120, -1, -1));

        lblTickets.setText("Tickets");
        getContentPane().add(lblTickets, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 260, -1, -1));

        lblDepartments.setText("Departamentos");
        getContentPane().add(lblDepartments, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 260, -1, -1));

        lblEval.setText("Evaluación");
        getContentPane().add(lblEval, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 260, -1, -1));

        lblBDC.setText("Base de datos");
        getContentPane().add(lblBDC, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 260, -1, -1));

        lblBottom.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/071770FB5.png"))); // NOI18N
        lblBottom.setToolTipText(null);
        getContentPane().add(lblBottom, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 670, 370));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDepartmentsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDepartmentsActionPerformed
        new department().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnDepartmentsActionPerformed

    private void btnServicesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnServicesActionPerformed
        new services().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnServicesActionPerformed

    private void btnLogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogOutActionPerformed
        if (JOptionPane.showConfirmDialog(null, "¿Seguro que desea salir?", "Salir",
                JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE) == JOptionPane.YES_OPTION) {
            this.dispose();
            new login().setVisible(true);
        }
    }//GEN-LAST:event_btnLogOutActionPerformed

    private void btnVehiclesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVehiclesActionPerformed
        new vehicles().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnVehiclesActionPerformed

    private void btnWorkersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnWorkersActionPerformed
        new workers().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnWorkersActionPerformed

    private void btnTicketsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTicketsActionPerformed
        new ticket().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnTicketsActionPerformed

    private void btnETicketsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnETicketsActionPerformed
        try {
            no_ticket = Integer.parseInt(JOptionPane.showInputDialog(null, "Ticket a evaluar", "Ingrese un número de ticket", JOptionPane.INFORMATION_MESSAGE));
            if (validateNoTicket()) {
                new evalTicket(no_ticket).setVisible(true);
                this.dispose();
            } else {
                JOptionPane.showMessageDialog(null, "El ticket aún no ha sido cerrado o no existe.");
            }
        } catch (NumberFormatException ex) {
        }

    }//GEN-LAST:event_btnETicketsActionPerformed

    private void btnBDCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBDCActionPerformed
        new knowledgeDB().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnBDCActionPerformed

    private void btnLogBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogBookActionPerformed
        new logBook().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnLogBookActionPerformed

    private void btnDependenciesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDependenciesActionPerformed
        new dependency().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnDependenciesActionPerformed

    private void btnLogBookMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLogBookMouseEntered
        lblLogBook.setVisible(true);
    }//GEN-LAST:event_btnLogBookMouseEntered

    private void btnLogBookMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLogBookMouseExited
        lblLogBook.setVisible(false);
    }//GEN-LAST:event_btnLogBookMouseExited

    private void btnServicesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnServicesMouseEntered
        lblServices.setVisible(true);
    }//GEN-LAST:event_btnServicesMouseEntered

    private void btnServicesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnServicesMouseExited
        lblServices.setVisible(false);
    }//GEN-LAST:event_btnServicesMouseExited

    private void btnVehiclesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVehiclesMouseEntered
        lblVehicles.setVisible(true);
    }//GEN-LAST:event_btnVehiclesMouseEntered

    private void btnVehiclesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVehiclesMouseExited
        lblVehicles.setVisible(false);
    }//GEN-LAST:event_btnVehiclesMouseExited

    private void btnWorkersMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnWorkersMouseEntered
        lblWorkers.setVisible(true);
    }//GEN-LAST:event_btnWorkersMouseEntered

    private void btnWorkersMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnWorkersMouseExited
        lblWorkers.setVisible(false);
    }//GEN-LAST:event_btnWorkersMouseExited

    private void btnDependenciesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDependenciesMouseEntered
        lblDependencies.setVisible(true);
    }//GEN-LAST:event_btnDependenciesMouseEntered

    private void btnDependenciesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDependenciesMouseExited
        lblDependencies.setVisible(false);
    }//GEN-LAST:event_btnDependenciesMouseExited

    private void btnDepartmentsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDepartmentsMouseEntered
        lblDepartments.setVisible(true);
    }//GEN-LAST:event_btnDepartmentsMouseEntered

    private void btnDepartmentsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDepartmentsMouseExited
        lblDepartments.setVisible(false);
    }//GEN-LAST:event_btnDepartmentsMouseExited

    private void btnETicketsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnETicketsMouseEntered
        lblEval.setVisible(true);
    }//GEN-LAST:event_btnETicketsMouseEntered

    private void btnETicketsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnETicketsMouseExited
        lblEval.setVisible(false);
    }//GEN-LAST:event_btnETicketsMouseExited

    private void btnBDCMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBDCMouseEntered
        lblBDC.setVisible(true);
    }//GEN-LAST:event_btnBDCMouseEntered

    private void btnBDCMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBDCMouseExited
        lblBDC.setVisible(false);
    }//GEN-LAST:event_btnBDCMouseExited

    private void btnTicketsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTicketsMouseEntered
        lblTickets.setVisible(true);
    }//GEN-LAST:event_btnTicketsMouseEntered

    private void btnTicketsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTicketsMouseExited
        lblTickets.setVisible(false);
    }//GEN-LAST:event_btnTicketsMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
        }
        //</editor-fold>

        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new main().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBDC;
    private javax.swing.JButton btnDepartments;
    private javax.swing.JButton btnDependencies;
    private javax.swing.JButton btnETickets;
    private javax.swing.JButton btnLogBook;
    private javax.swing.JButton btnLogOut;
    private javax.swing.JButton btnServices;
    private javax.swing.JButton btnTickets;
    private javax.swing.JButton btnVehicles;
    private javax.swing.JButton btnWorkers;
    private javax.swing.JLabel lblBDC;
    private javax.swing.JLabel lblBottom;
    private javax.swing.JLabel lblDepartments;
    private javax.swing.JLabel lblDependencies;
    private javax.swing.JLabel lblEval;
    private javax.swing.JLabel lblLogBook;
    private javax.swing.JLabel lblServices;
    private javax.swing.JLabel lblTickets;
    private javax.swing.JLabel lblVehicles;
    private javax.swing.JLabel lblWorkers;
    // End of variables declaration//GEN-END:variables
}
