package interfaces;

import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;

/**
 *
 * @author barreola
 */
public class main extends javax.swing.JFrame {

    public main() {
        try {
            initComponents();
            this.setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE); //Desactiva el botón de cerrar
            setLocationRelativeTo(null); //Centra el jFrame
            UIManager.setLookAndFeel("java.swing.plaf.gtk.GTKLookAndFeel"); //Da el estilo al jFrame
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | UnsupportedLookAndFeelException ex) {
            Logger.getLogger(main.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnDepartments = new javax.swing.JButton();
        btnLogBook = new javax.swing.JButton();
        btnETickets = new javax.swing.JButton();
        btnBDC = new javax.swing.JButton();
        btnTickets = new javax.swing.JButton();
        btnServices = new javax.swing.JButton();
        btnVehicles = new javax.swing.JButton();
        btnWorkers = new javax.swing.JButton();
        btnReturn = new javax.swing.JButton();
        lblBottom = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Principal");
        setName("frmMain"); // NOI18N
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnDepartments.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/business_office.png"))); // NOI18N
        btnDepartments.setToolTipText("Departamentos");
        btnDepartments.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnDepartments.setBorderPainted(false);
        btnDepartments.setContentAreaFilled(false);
        btnDepartments.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDepartmentsActionPerformed(evt);
            }
        });
        getContentPane().add(btnDepartments, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 200, -1, -1));

        btnLogBook.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/address_book.png"))); // NOI18N
        btnLogBook.setToolTipText("Bitácora");
        btnLogBook.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnLogBook.setBorderPainted(false);
        btnLogBook.setContentAreaFilled(false);
        btnLogBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogBookActionPerformed(evt);
            }
        });
        getContentPane().add(btnLogBook, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 100, -1, -1));

        btnETickets.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/attendance_list.png"))); // NOI18N
        btnETickets.setToolTipText("Evaluar ticket");
        btnETickets.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnETickets.setBorderPainted(false);
        btnETickets.setContentAreaFilled(false);
        btnETickets.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnETicketsActionPerformed(evt);
            }
        });
        getContentPane().add(btnETickets, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 200, -1, -1));

        btnBDC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/batch_process.png"))); // NOI18N
        btnBDC.setToolTipText("BD Conocimiento");
        btnBDC.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnBDC.setBorderPainted(false);
        btnBDC.setContentAreaFilled(false);
        getContentPane().add(btnBDC, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 200, -1, -1));

        btnTickets.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/edit.png"))); // NOI18N
        btnTickets.setToolTipText("Tickets");
        btnTickets.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnTickets.setBorderPainted(false);
        btnTickets.setContentAreaFilled(false);
        btnTickets.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTicketsActionPerformed(evt);
            }
        });
        getContentPane().add(btnTickets, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 200, -1, -1));

        btnServices.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/services.png"))); // NOI18N
        btnServices.setToolTipText("Servicios");
        btnServices.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnServices.setBorderPainted(false);
        btnServices.setContentAreaFilled(false);
        btnServices.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnServicesActionPerformed(evt);
            }
        });
        getContentPane().add(btnServices, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 100, -1, -1));

        btnVehicles.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/cars.png"))); // NOI18N
        btnVehicles.setToolTipText("Vehículos");
        btnVehicles.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnVehicles.setBorderPainted(false);
        btnVehicles.setContentAreaFilled(false);
        btnVehicles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVehiclesActionPerformed(evt);
            }
        });
        getContentPane().add(btnVehicles, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 100, -1, -1));

        btnWorkers.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/group.png"))); // NOI18N
        btnWorkers.setToolTipText("Trabajadores");
        btnWorkers.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnWorkers.setBorderPainted(false);
        btnWorkers.setContentAreaFilled(false);
        btnWorkers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnWorkersActionPerformed(evt);
            }
        });
        getContentPane().add(btnWorkers, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 100, -1, -1));

        btnReturn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/outbox.png"))); // NOI18N
        btnReturn.setToolTipText("Cerrar sesión");
        btnReturn.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnReturn.setBorderPainted(false);
        btnReturn.setContentAreaFilled(false);
        btnReturn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReturnActionPerformed(evt);
            }
        });
        getContentPane().add(btnReturn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 320, -1, -1));

        lblBottom.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/071770FB5.png"))); // NOI18N
        getContentPane().add(lblBottom, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 590, 370));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDepartmentsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDepartmentsActionPerformed

    }//GEN-LAST:event_btnDepartmentsActionPerformed

    private void btnServicesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnServicesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnServicesActionPerformed

    private void btnReturnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReturnActionPerformed
        this.dispose();
        new login().setVisible(true);
    }//GEN-LAST:event_btnReturnActionPerformed

    private void btnLogBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogBookActionPerformed
        this.dispose();
        new logBook().setVisible(true);
    }//GEN-LAST:event_btnLogBookActionPerformed

    private void btnVehiclesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVehiclesActionPerformed
        this.dispose();
        new vehicles().setVisible(true);
    }//GEN-LAST:event_btnVehiclesActionPerformed

    private void btnWorkersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnWorkersActionPerformed
        this.dispose();
        new workers().setVisible(true);
    }//GEN-LAST:event_btnWorkersActionPerformed

    private void btnTicketsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTicketsActionPerformed
        
    }//GEN-LAST:event_btnTicketsActionPerformed

    private void btnETicketsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnETicketsActionPerformed
        this.dispose();
        new evalTicket().setVisible(true);
    }//GEN-LAST:event_btnETicketsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new main().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBDC;
    private javax.swing.JButton btnDepartments;
    private javax.swing.JButton btnETickets;
    private javax.swing.JButton btnLogBook;
    private javax.swing.JButton btnReturn;
    private javax.swing.JButton btnServices;
    private javax.swing.JButton btnTickets;
    private javax.swing.JButton btnVehicles;
    private javax.swing.JButton btnWorkers;
    private javax.swing.JLabel lblBottom;
    // End of variables declaration//GEN-END:variables
}
