package interfaces;

import com.mxrck.autocompleter.TextAutoCompleter;
import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.JFrame;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.Calendar;
import javax.swing.JOptionPane;

public class ticket extends javax.swing.JFrame {

    private String status;
    TextAutoCompleter autocomplete;

    public ticket() {
        initComponents();
        formatJFrame();
        autocomplete = new TextAutoCompleter(txtNoWorker);
        autocomplete.setCaseSensitive(false);
        autocomplete.setMode(0);
        autocomplete.addItems(setNoWorkerCompletion());
    }

    private void formatJFrame() {
        try {
            this.setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE); //Desactiva el botón de cerrar
            setLocationRelativeTo(null); //Centra el jFrame
            UIManager.setLookAndFeel("com.sun.java.swing.plaf.gtk.GTKLookAndFeel"); //Da el estilo al jFrame
            //UIManager.setLookAndFeel( "com.seaglasslookandfeel.SeaGlassLookAndFeel" ); //Da el estilo al jFrame
            this.pack();
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | UnsupportedLookAndFeelException ex) {
            ex.getMessage();
        }
    }

    private ArrayList setNoWorkerCompletion() {
        try {
            ArrayList<Integer> regNo = new ArrayList<>();
            DriverManager.registerDriver(new org.gjt.mm.mysql.Driver());
            Connection connection = DriverManager.getConnection("jdbc:mysql://localhost/PI_5J?useServerPrepStmts=true", "root", "root");
            Statement select = connection.createStatement();
            ResultSet result = select.executeQuery("SELECT no_trabajador from Workers");

            while (result.next()) {
                regNo.add(result.getInt("no_trabajador"));
            }

            connection.close();
            return regNo;
        } catch (SQLException ex) {
            return null;
        }
    }

    public java.sql.Date getDate() {
        Calendar calendar = Calendar.getInstance();
        java.sql.Date date = new java.sql.Date(calendar.getTime().getTime());
        return date;
    }

    public boolean isEmpty() {
        return !(txtDesc.getText().isEmpty() || txtLocation.getText().isEmpty()
                || txtMotive.getText().isEmpty());
    }

    @Override
    public Image getIconImage() {
        Image retValue = Toolkit.getDefaultToolkit().
                getImage(ClassLoader.getSystemResource("icons/program_icon.png"));
        return retValue;
    }

    private void getNoTicket() {
        try {
            DriverManager.registerDriver(new org.gjt.mm.mysql.Driver());

            Connection connection = DriverManager.getConnection("jdbc:mysql://localhost/PI_5J?useServerPrepStmts=true", "root", "root");
            ResultSet result;
            Statement select = connection.createStatement();
            result = select.executeQuery("SELECT no_ticket FROM Ticket ORDER BY no_ticket desc limit 1;");

            while (result.next()) {
                JOptionPane.showMessageDialog(this, "Ticket número: " + result.getInt("no_ticket") + " añadido.",
                        "Ticket añadido", JOptionPane.INFORMATION_MESSAGE);
            }
        } catch (SQLException ex) {
        }
    }

    private String getWorkerName() {
        try {
            DriverManager.registerDriver(new org.gjt.mm.mysql.Driver());

            Connection connection = DriverManager.getConnection("jdbc:mysql://localhost/PI_5J?useServerPrepStmts=true", "root", "root");
            ResultSet result;
            Statement select = connection.createStatement();
            result = select.executeQuery("SELECT nombre from Workers where no_trabajador =" + Integer.valueOf(txtNoWorker.getText()));

            while (result.next()) {
                return result.getString("nombre");
            }
        } catch (SQLException ex) {
            return null;
        }
        return null;
    }

    private boolean workerExists() {
        return getWorkerName() != null;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblStatus = new javax.swing.JLabel();
        lblMotive = new javax.swing.JLabel();
        lblLocation = new javax.swing.JLabel();
        lblDesc = new javax.swing.JLabel();
        txtMotive = new javax.swing.JTextField();
        txtLocation = new javax.swing.JTextField();
        btnCreate = new javax.swing.JButton();
        btnReturn = new javax.swing.JButton();
        btnClosed = new javax.swing.JButton();
        btnOpen = new javax.swing.JButton();
        lblNoWorker = new javax.swing.JLabel();
        txtNoWorker = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtDesc = new javax.swing.JTextArea();
        lblBottom = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Ticket");
        setIconImage(getIconImage());
        setMaximumSize(new java.awt.Dimension(343, 351));
        setMinimumSize(new java.awt.Dimension(343, 351));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblStatus.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        lblStatus.setText("Status:");
        getContentPane().add(lblStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 40, -1, -1));

        lblMotive.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        lblMotive.setText("Motivo:");
        getContentPane().add(lblMotive, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, -1, -1));

        lblLocation.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        lblLocation.setText("Ubicación:");
        getContentPane().add(lblLocation, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 90, -1, -1));

        lblDesc.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        lblDesc.setText("Descripción:");
        getContentPane().add(lblDesc, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, -1, -1));

        txtMotive.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        getContentPane().add(txtMotive, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 310, -1));

        txtLocation.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        getContentPane().add(txtLocation, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 130, 250, -1));

        btnCreate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/add.png"))); // NOI18N
        btnCreate.setToolTipText("Crear");
        btnCreate.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnCreate.setBorderPainted(false);
        btnCreate.setContentAreaFilled(false);
        btnCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateActionPerformed(evt);
            }
        });
        getContentPane().add(btnCreate, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 310, 60, 60));

        btnReturn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/left.png"))); // NOI18N
        btnReturn.setToolTipText("Regresar");
        btnReturn.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnReturn.setBorderPainted(false);
        btnReturn.setContentAreaFilled(false);
        btnReturn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReturnActionPerformed(evt);
            }
        });
        getContentPane().add(btnReturn, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 310, 60, 60));

        btnClosed.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/lock_closed.png"))); // NOI18N
        btnClosed.setToolTipText("Cerrado");
        btnClosed.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnClosed.setBorderPainted(false);
        btnClosed.setContentAreaFilled(false);
        btnClosed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClosedActionPerformed(evt);
            }
        });
        getContentPane().add(btnClosed, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 40, -1, -1));

        btnOpen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/lock_open.png"))); // NOI18N
        btnOpen.setToolTipText("Abierto");
        btnOpen.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnOpen.setBorderPainted(false);
        btnOpen.setContentAreaFilled(false);
        btnOpen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOpenActionPerformed(evt);
            }
        });
        getContentPane().add(btnOpen, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 40, -1, -1));

        lblNoWorker.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        lblNoWorker.setText("Número de trabajador:");
        getContentPane().add(lblNoWorker, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        txtNoWorker.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        getContentPane().add(txtNoWorker, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 160, -1));

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setToolTipText(null);

        txtDesc.setColumns(20);
        txtDesc.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        txtDesc.setRows(5);
        txtDesc.setTabSize(4);
        txtDesc.setToolTipText(null);
        jScrollPane1.setViewportView(txtDesc);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, 310, 150));

        lblBottom.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/071770FB5.png"))); // NOI18N
        lblBottom.setToolTipText(null);
        getContentPane().add(lblBottom, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 630, 370));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnOpenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOpenActionPerformed
        status = "abierto";
        btnOpen.setVisible(false);
        btnClosed.setVisible(true);
    }//GEN-LAST:event_btnOpenActionPerformed

    private void btnClosedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClosedActionPerformed
        status = "cerrado";
        btnClosed.setVisible(false);
        btnOpen.setVisible(true);
    }//GEN-LAST:event_btnClosedActionPerformed

    private void btnReturnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReturnActionPerformed
        if (JOptionPane.showConfirmDialog(null, "¿Seguro que desea salir?\nTodos los datos no guardados se perderán", "Confirmar",
                JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE) == JOptionPane.YES_OPTION) {
            this.dispose();
            new main().setVisible(true);
        }
    }//GEN-LAST:event_btnReturnActionPerformed

    private void btnCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateActionPerformed
        if (isEmpty()) {
            outer:
            try {
                DriverManager.registerDriver(new org.gjt.mm.mysql.Driver());

                Connection connection = DriverManager.getConnection("jdbc:mysql://localhost/PI_5J?useServerPrepStmts=true", "root", "root");
                PreparedStatement insert = connection.prepareStatement("INSERT INTO Ticket" + " VALUES(null,?,?,?,?,?,?,?)");

                if (workerExists()) {
                    insert.setString(1, getWorkerName());
                } else {
                    JOptionPane.showMessageDialog(null, "El trabajador no existe", "Error al añadir", JOptionPane.INFORMATION_MESSAGE);
                    break outer;
                }

                insert.setString(2, txtDesc.getText());
                insert.setString(3, txtMotive.getText());
                insert.setDate(4, getDate());
                insert.setString(5, status);
                insert.setString(6, txtLocation.getText());
                insert.setInt(7, Integer.parseInt(txtNoWorker.getText()));

                insert.executeUpdate();
                insert.close();

                getNoTicket();

            } catch (SQLException ex) {
                ex.getMessage();
            }
        } else {
            JOptionPane.showMessageDialog(null, "Debe completar todos los campos.", "Error al añadir", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btnCreateActionPerformed

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {

        }
        //</editor-fold>

        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new ticket().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClosed;
    private javax.swing.JButton btnCreate;
    private javax.swing.JButton btnOpen;
    private javax.swing.JButton btnReturn;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblBottom;
    private javax.swing.JLabel lblDesc;
    private javax.swing.JLabel lblLocation;
    private javax.swing.JLabel lblMotive;
    private javax.swing.JLabel lblNoWorker;
    private javax.swing.JLabel lblStatus;
    private javax.swing.JTextArea txtDesc;
    private javax.swing.JTextField txtLocation;
    private javax.swing.JTextField txtMotive;
    private javax.swing.JTextField txtNoWorker;
    // End of variables declaration//GEN-END:variables
}
